### ISSUE TITLE
Error: libcups.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by marisaroude** [grandchef/node-printer#9]
Hi! I need help with this problem. I'm deploying in vercel but i have this error:

Error: libcups.so.2: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at r.<computed>.e._load (/var/task/___vc/__launcher/bridge-server-72TT5FOD.js:1:1574)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/task/node_modules/@damonsmith/node-printer/lib/printer-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'ERR_DLOPEN_FAILED'
}
INIT_REPORT Init Duration: 1022.90 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by mazinsw** [comment]
Hi, on linux based system it's required to install libcups2, try this command: `sudo apt-get install libcups2-dev`

**Comment by marisaroude** [comment]
Hi! thank you for your reply.
Yes, I have the package installed. I do not understand what I am missing.
![image](https://github.com/grandchef/node-printer/assets/81636065/53406be5-601d-4da2-a625-23dc68a00307)

**Comment by marisaroude** [comment]
Is it necessary to use electron? Because I am not implementing it

**Comment by mazinsw** [comment]
It is tested on electron, but it should work on node too, this problem seems a missing system lib path, check if this path get from this command `whereis  libcups.so.2` is listed here  by this command `cat /etc/ld.so.conf.d/*`

**Comment by marisaroude** [comment]
I got this result, should I add the following line in one of the .conf files?

` /usr/lib/x86_64-linux-gnu/libcups.so.2
`

![image](https://github.com/grandchef/node-printer/assets/81636065/5d086465-960a-4cff-939c-1f407fffb802)

**Comment by mazinsw** [comment]
It already contains the path, can be a problem on node_modules installation folder, did you remove nodes_modules and reinstalled?
if not solve check if this command `ldd node_modules/@grandchef/node-printer/lib/binding/node_printer.node | grep libcups` output like this: `libcups.so.2 => /usr/lib/x86_64-linux-gnu/libcups.so.2 (0x00007efde22b4000)`
if different try creating a alias: `sudo ln -s /usr/lib/x86_64-linux-gnu/libcups.so.2 /lib/x86_64-linux-gnu/libcups.so.2`

directory `/lib/x86_64-linux-gnu/` must exists, if not, make with: `sudo mkdir -p /lib/x86_64-linux-gnu/`

![image](https://github.com/grandchef/node-printer/assets/7927014/8a66c2d4-7c33-4165-b010-69e83af51dc3)

**Comment by marisaroude** [comment]
I tried to remove node_modules and reinstall the dependencies, but it didn't work.

I understand that this command `ldd node_modules/@grandchef/node-printer/lib/binding/node_printer.node | grep libcups r`eturns fine.

What I find strange is that I get perfect execution and printing on the thermal printer when I play the GraphQL mutation that performs this action on localhost.

I think maybe I am having problems with the LD_LIBRARY_PATH environment variable, is it possible?

![image](https://github.com/grandchef/node-printer/assets/81636065/96c6e652-9b1e-4d8b-818d-a58e5ffbccdf)

**Comment by marisaroude** [comment]
Replace @grandchef with @damonsmith as that was the one I installed.

**Comment by mazinsw** [comment]
Now its get more clear, the build was made at a different OS base than vercel are try to run, this explain why it is not finding the library, try to build at the same OS/Container than vercel

**Comment by marisaroude** [comment]
Like Docker? 
Before implementing printing with the thermal printer, I had already deployed it and it worked perfectly. 
Sorry for so many questions, it's the first time I implement a thermal printer and deploy in vercel.

**Comment by marisaroude** [comment]
I was able to perform different queries and other mutations, for example, add, update, get, and others.

**Comment by mazinsw** [comment]
Yes, docker has many base container like, alpine, ubuntu, debian, you must build with the same base container than vercel https://vercel.com/docs/deployments/build-image

I undersant that when not loaded the library the error does not occurr, this explain why some queries does not trigger the error

**Comment by marisaroude** [comment]
Perfect, I'll go that way.
Thank you very much!
